export * from './page-action.home.buscar-conteudo'
export * from './page-action.transparencia.buscar-relatorios'
export * from './page-action.admin.salvar-conteudo'
export * from './page-action.admin.gerir-relatorios'
export * from './page-action.admin.gerir-certificacoes'
export * from './page-action.admin.gerir-anexos'
export * from './page-action.admin.gerir-classificacoes'
